[workspace]
resolver = "3"
members = [
    "lsf",
    "cardinal-sdk",
    "fswalk",
    "namepool",
    "was",
    "lsf-tui",
    "fs-icon",
    "query-segmentation",
    "cardinal-native",
]
exclude = ["cardinal"]
